### ISSUE TITLE
test jednostkowy

### ISSUE THREAD

**Issue by isawmakurat** [DanielSkwierawski/workScheduler2#2]
workScheduler2/src/main/java/com/danielskwierawski/workScheduler2/Jsonator.java#L12

przenieść do testu jednostkowego, zamiast pisać main

**Comment by DanielSkwierawski** [comment]
done
https://github.com/DanielSkwierawski/workScheduler2/tree/master/src/test/java/com/danielskwierawski/workScheduler2/model
